
spring:
  application:
    name: AppRestauranteDJ

  datasource:
    url: jdbc:postgresql://localhost:5432/BDrestauranteDJ
    username: postgres
    password: samuel
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Configurações para o perfil de desenvolvimento utilizando H2
---

spring:
   server.port=8085
   profiles= dev
   h2.console.enabled=true

datasource:
    url: jdbc:h2:mem:BDrestauranteDJ
    username: sa
    password: password
    driver-class-name: org.h2.Driver

jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.H2Dialect

  


