server:
  port: 8081
  servlet:
    context-path: /AppRestauranteDJ
spring:
  application:
    name: AppRestauranteDJ

  datasource:
    url: jdbc:postgresql://localhost:5432/BDrestauranteDJ
    username: postgres
    password: samuel
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Configurações para o perfil de desenvolvimento utilizando H2
---

spring:
  profiles: dev

  # Configurando o H2 para usar a porta 8082
  h2:
    console:
      enabled: true
    port: 8082

  # Configurações do Swagger
  swagger:
    port: 8083  # Alterando a porta do Swagger para evitar conflitos

logging:
  level:
    root: DEBUG