server:
  port: 8765
  servlet:
    context-path: /AppRestauranteDJ

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: Pedido
          uri: lb://Pedido
          predicates:
            - Path=/Pedido/**
        - id: Produto
          uri: lb://Produto
          predicates:
            - Path=/Produto/**
        - id: ItemPedido
          uri: lb://ItemPedido
          predicates:
            - Path=/ItemPedido/**

  datasource:
    url: jdbc:postgresql://localhost:5432/BDrestauranteDJ
    username: postgres
    password: samuel
    driver-class-name: org.postgresql.Driver
  hikari:
    maximum-pool-size: 10

  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  level:
    root: DEBUG

swagger:
  enabled: true
  port: 8100
